# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Untaint
version:      1.25
version_from: lib/CGI/Untaint.pm
installdirs:  site
requires:
    Test::More:                    0.11
    UNIVERSAL::require:            0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
